# Generated by Django 5.2.8 on 2025-11-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('generated_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('students_required', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('comp_studies', 'Computer Studies'), ('engineering', 'Engineering'), ('health_sci', 'Health Sciences'), ('business', 'Business And Management'), ('science', 'Science'), ('math', 'Mathematics'), ('education', 'Education'), ('humanities', 'Humanities'), ('arts_and_design', 'Arts and Design'), ('others', 'Others')], default='general', max_length=30)),
                ('help_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_helper', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('total_credits', models.IntegerField(default=0)),
                ('students_helped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=100)),
                ('radius_km', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='problem_attachments/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='peerhelp.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.problem')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='solution_attachments/')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='peerhelp.solution')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.user'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_received', models.FloatField(default=0.0)),
                ('problems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.problem')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.review')),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('badges_count', models.IntegerField(default=0)),
                ('bio', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerhelp.user')),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
