# Generated by Django 5.2.8 on 2025-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_document_hast',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
