# Generated by Django 5.2.8 on 2025-11-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='in_person_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='meeting_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='meeting_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
