# Generated by Django 5.2.8 on 2025-11-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0002_problem_in_person_mode_problem_meeting_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='owner_meeting_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='owner_meeting_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solver_meeting_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solver_meeting_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
