# Generated by Django 5.2.8 on 2025-11-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0002_userprofile_id_document_hast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_document_hast',
            new_name='id_document_hash',
        ),
    ]
