# Generated by Django 5.2.8 on 2025-11-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0003_problem_owner_meeting_reply_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISummary',
        ),
    ]
