# Generated by Django 5.2.8 on 2025-12-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerhelp', '0005_aisummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISummary',
        ),
    ]
